### ISSUE TITLE
 Core Devs 51 Meeting Agenda

### ISSUE THREAD

**Issue by luckyparadise** [filecoin-project/tpm#120]
# Filecoin Core Devs Meeting 51 Agenda
- **Meeting Date & Time**: Friday, November 11, 2022 @ [00:00 UTC] (https://www.timeanddate.com/worldclock/converter.html?iso=20210903T180000&p1=1440)
- Meeting will be recorded. 

# **Agenda**
- Welcome & Agenda
- FIP: Improving EC security with Consistent Broadcast
- HC discussion 
- Q&A

**Comment by adlrocha** [comment]
Hi, all. We think at ConsensusLab that it would be great if we can include in the next meeting a discussion of the following [FIP proposal](https://github.com/filecoin-project/FIPs/discussions/501) even if that means postponing the discussion about HC again. The proposed change is potentially more short-term and can easily be pushed to the network. Thanks :pray: 

//cc @guy.goren @jsoares

**Comment by willscott** [comment]
This issue claims the call will be at
> Thursday, November 3, 2022 @ [16:00 UTC]
(with a timezone link pointing to 2021)

The general policy for these meetings as I understand them is that they are:
> Even-numbered months (February, April, June, August, October, and December) are hosted at 16:00 UTC. Odd-numbered months (January, March, May, July, September, and November) are hosted at 00:00 UTC.

Can someone clarify when this will happen?

**Comment by luckyparadise** [comment]
> 

Hey @adlrocha can we perhaps have both conversations during the call? As we do not have other things to discuss at the meeting. What would you prefer?

**Comment by kaitlin-beegle** [comment]
> This issue claims the call will be at
> 
> > Thursday, November 3, 2022 @ [16:00 UTC]
> > (with a timezone link pointing to 2021)
> 
> The general policy for these meetings as I understand them is that they are:
> 
> > Even-numbered months (February, April, June, August, October, and December) are hosted at 16:00 UTC. Odd-numbered months (January, March, May, July, September, and November) are hosted at 00:00 UTC.
> 
> Can someone clarify when this will happen?

You're right, there was just a typo in the agenda; looks like it's been fixed.  In general, you can always refer to the calendar hold as the source of truth.  Thanks!

**Comment by adlrocha** [comment]
> Hey @adlrocha can we perhaps have both conversations during the call? As we do not have other things to discuss at the meeting. What would you prefer?

Sure, @luckyparadise, we can discuss both in the call. I will ask @guy.goren if he wants to share some introductory slides for the discussion, and I may need to make some changes on mine (but I'll ping you tomorrow if this is the case).

On another note, it will be 1am on our time-zones, so we would really appreciate if we could go first (in case new things end up being brought up for discussion). Thanks! :pray:

**Comment by luckyparadise** [comment]
No p @adlrocha ! I will set you up to go first. Please share your updated slides by tomorrow. Thank you!
