### ISSUE TITLE
Filecoin Core Devs Meeting 16 Agenda

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/tpm#36]
# Filecoin Core Devs Meeting 16 Agenda

- Meeting Date/Time: **Thursday 22 April 2021, [16:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/16-00)**
- Recording

# Agenda

- Any latest updates/hurdles from Filecoin implementations
  - [Lotus](https://github.com/filecoin-project/lotus)
  - [Forest](https://github.com/ChainSafe/forest)
  - [Fuhon](https://github.com/filecoin-project/cpp-filecoin)
  - [Venus](https://github.com/filecoin-project/go-filecoin)
  - [Filecoin Foundation](https://fil.org/)
- [FIP 0013 update ](https://github.com/filecoin-project/FIPs/pull/94)
- [Network v12 upgrade](https://github.com/filecoin-project/community/discussions/74#discussioncomment-642326)
- Community
- Q&A

**Comment by cryptoquick** [comment]
The date is slightly off there, @jennijuju :)

**Comment by jennijuju** [comment]
> The date is slightly off there, @jennijuju :)

oh thank you for catching that!

**Comment by Fatman13** [comment]
Do we have the recording of #16?
