### ISSUE TITLE
Draft notes from meeting #22

### ISSUE THREAD

**Issue by gagizoned** [filecoin-project/tpm#53]
# Filecoin Core Devs Meeting 22 - 2021-07-15

- Meeting Date/Time: **Thursday, July 15  2021, [16:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/16-00)**
- Meeting Recording:
- Attendance: Forest (Chainsafe), Fuhon (Soramitsu), Lotus (PL), Venus (IPFSForce), Filecoin Foundation, and Community representatives

Lotus:

- We are testing 1.11.0 since we are adding 3 months of work
- A lot of important things are now in master:

   - Splitstore (which has online garbage collection) which might be interesting to review

- We are focusing on integration tests, we changed the way we do tests
- Monitoring Hyperdrive, we shipped the 1.10.1 release for Hotfix purposes, looking good so far

Forest:

- We have Prometheus metrics now
- Team is working on UX for our CLI
- Also, we will work on documentation from next week
- V13 upgrade - we have almost the entire implementation, we will be on the mainnet soon
- Security audit - major things are fixed, a couple of small things still to sort out

Fuhon:

- Working on preparation for security audit
- Also, we are testing our node with Lotus on interoperability net. We have bugs we are sorting out there.
- Issues we are facing on the Mainnet node - we can’t access memory in LibC

Venus:

- We achieved a big thing, we passed the security audit
- The main achievement of Venus is that we have the security audit done, and got the final report published;
- We did the v1.0.0 is release
- Now working on incubation launch preparation.

Filecoin Foundation:

- Hyperdrive launch  - awesome job, we are still collecting feedback from the community
- We would be extending the bounty program to all the implementation, we will reach out to the team to see how we can make it happen.
- Foundation is hiring, we have several open positions

---

Discussion on the call:

Price list update - Relevant PR's for review:

- [https://github.com/filecoin-project/go-state-types/pull/30/files#diff-c978f04d14be47fba23d62d4c8bccee128a88b9bebd8a30ee6b03fa448405996R17](https://github.com/filecoin-project/go-state-types/pull/30/files#diff-c978f04d14be47fba23d62d4c8bccee128a88b9bebd8a30ee6b03fa448405996R17)
- [https://github.com/filecoin-project/lotus/pull/6766](https://github.com/filecoin-project/lotus/pull/6766)

Lotus issue discussed on the call, other implementations to review:

[https://github.com/filecoin-project/lotus/issues/3613](https://github.com/filecoin-project/lotus/issues/3613) - Lotus fetches drand from chain backward with null blocks while specs fetch forward

---

The last item on the agenda is:
**FIP16** ([https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0016.md](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0016.md)) discussion:

- A lot of the implementations teams it's a good idea
- We have a lot of comments on the FIP, that should be reviewed by the teams
- We should do a survey in order to determine the priority of this implementation and how immediate the demand for this is.

**Comment by arajasek** [comment]
Pulled into #54 :)
