### ISSUE TITLE
Meeting notes for meeting 25  - Draft version

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/tpm#62]
# Filecoin Core Devs Meeting notes #25 - 2021-08-26

- Meeting Date/Time: **Thursday, August 26th 2021, [16:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/16-00)**
- Meeting Recording:
- Attendance: Forest (Chainsafe), Fuhon (Soramitsu), Lotus (PL), Venus (IPFSForce), Filecoin Foundation, and Community representatives

### Updates for the week

Lotus:

- We released [1.11.2 RC1](https://github.com/filecoin-project/lotus/releases/tag/v1.11.2-rc1), we are working on bug fixes for now
- Working further on the RC train which introduces [DagStore](https://docs.filecoin.io/mine/lotus/dagstore/#conceptual-overview) and other features

Forest:

- Not much heavy lifting, working on Docs for releases
- Debugging some issues with help from the Lotus + actors team

Fuhon:

- We discovered some issues and we are solving
- We are working on deals and testing them on testnet
- We plan to release on September 10th but will keep everyone posted

Venus:

- We plan to enable modules for market features
- We are solving issues that we are facing on the platform and for the miners, so we can share rewards in fairness
- The team will share plans for the rewards system they have, so we can review it

Filecoin Foundation:

- We are taking a look at some reported bugs, thanks to the PL team for stepping in to help
- Foundation is taking hosting of the Core devs call

---

### Open Discussions on the call:

- SnapDeals presentation and discussion - [https://github.com/filecoin-project/FIPs/issues/145](https://github.com/filecoin-project/FIPs/issues/145)

**Comment by kaitlin-beegle** [comment]
Closing; final notes have been updated and adopted!
