### ISSUE TITLE
Filecoin Core Devs Meeting #30 - Agenda

### ISSUE THREAD

**Issue by kaitlin-beegle** [filecoin-project/tpm#75]
# Filecoin Core Devs Meeting 30 Agenda
* **Meeting Date & Time:** Thursday, November 4 @ [16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20210903T180000&p1=1440)
* Meeting will be recorded. 

# Agenda
* Discussing updates, hurdles, questions, and challenges from Filecoin implementations:
    * [Lotus](https://github.com/filecoin-project/lotus)
    * [Forest](https://github.com/ChainSafe/forest)
    * [Fuhon](https://github.com/filecoin-project/cpp-filecoin)
         * C++ Actors 
         * Open Source PM Best Practices
    * [Venus](https://github.com/filecoin-project/venus)
* Updates from [Filecoin Foundation](https://fil.org/)
* Q&A

**Comment by Fatman13** [comment]
Meeting notes stopped updating @ meeting 26?
